# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='uploads/items')),
                ('percentage', models.CharField(choices=[('50%', '50%'), ('100%', '100%')], default='100%', max_length=20)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/items')),
                ('portfolioitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Item')),
            ],
            options={
                'verbose_name': 'Item Image',
                'verbose_name_plural': 'Item Images',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='items', to='main.ItemCategory', verbose_name='Categories'),
        ),
    ]
