# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='category_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
