# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_itemcategory_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default=2, max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
