# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160126_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='items', to='main.ItemCategory', verbose_name='\u053f\u0561\u057f\u0565\u0563\u0578\u0580\u056b\u0561\u0576\u0565\u0580'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='\u0546\u056f\u0561\u0580\u0561\u0563\u0580\u0578\u0582\u0569\u0575\u0578\u0582\u0576'),
        ),
        migrations.AlterField(
            model_name='item',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/items', verbose_name='\u0546\u056f\u0561\u0580'),
        ),
        migrations.AlterField(
            model_name='item',
            name='percentage',
            field=models.CharField(choices=[('50%', '50%'), ('100%', '100%')], default='100%', max_length=20, verbose_name='\u054f\u0578\u056f\u0578\u057d\u0561\u0579\u0561\u0583'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=120, verbose_name='\u054e\u0565\u0580\u0576\u0561\u0563\u056b\u0580'),
        ),
    ]
