BBBB BBBB

BB BBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
    BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Please correct the errors below.') XXXXXX
    BBBBBB
XXXXXX
BBBBB
